AV 17.01.2006

* Summary

Mutex lock occurred again in PyCool and PyCoolUtilities.

Platforms?
Problem occurs for both SLC and Windows.
Problem occurs for all three backends.

Reproducibility?
Sometimes a segmentation fault is seen instead.
Sometimes the same test runs with no problems.
Marco claims an empty printout solves it:
according to Andrea, sometimes it does, sometimes it does not.

Cause?
Problem seems related to boost and ROOT TClass destructor.

* Test case

See test case test_MutexLock.py:
  \rm test_MutexLock.out ; python test_MutexLock.py > & test_MutexLock.out
Sometimes this hangs, sometimes it does not.

The problem is definitely in the line
"not dbExists( targetConnectString )".
This is where sometimes the program hangs.
It is also where on the screen the message 
"free(): invalid pointer" is disaplyed.

The message "free(): invalid pointer" 
could be very useful to identify the source of the problem.
It is probably printed out by the buggy code.
Especially, it is ALWAYS reproducible.

The test seemed to hang always until I added 
printouts, now it hangs only sometimes.
Note that there are probably different streams:
on the screen, the message "free(): invalid pointer"
is printed between "Entering test_dbExists"
and "About to test existence of non-existent database",
while in thge logfile all messages are at the end.




 